# Portuguese (Brazil) translations for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# Gabriel Wainer, 2013
# vmoliveira <volmar.oliveira.jr@gmail.com>, 2013
msgid ""
msgstr ""
"Project-Id-Version:  Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-07-11 06:00+0000\n"
"PO-Revision-Date: 2014-04-19 01:30+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Portuguese (Brazil) "
"(http://www.transifex.com/projects/p/keystone/language/pt_BR/)\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr "%s não pode estar vazio."

#: keystone/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr "%(property_name)s não pode ter menos de %(min_length)s caracteres."

#: keystone/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr "%(property_name)s não deve ter mais de %(max_length)s caracteres."

#: keystone/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr "%(property_name)s não é um %(display_expected_type)s"

#: keystone/cli.py:139
msgid "keystone-manage pki_setup is not recommended for production use."
msgstr ""

#: keystone/cli.py:158
msgid "keystone-manage ssl_setup is not recommended for production use."
msgstr ""

#: keystone/exception.py:49
msgid "missing exception kwargs (programmer error)"
msgstr "ausente exceção kwargs (erro do programador)"

#: keystone/exception.py:79
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:88
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""
"A data não está no formato especificado. O servidor não pôde realizar a "
"requisição pois ela está mal formada ou incorreta. Assume-se que o "
"cliente está com erro."

#: keystone/exception.py:97
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""
"Comprimento de string excedido. O comprimento de string '%(string)s' "
"excedeu o limite da coluna %(type)s(CHAR(%(length)d))."

#: keystone/exception.py:103
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""
"Atributo de requisição %(attribute)s deve ser menor ou igual a %(size)i. "
"O servidor não pôde atender a requisição porque o tamanho do atributo é "
"inválido (muito grande). Assume-se que o cliente está em erro."

#: keystone/exception.py:113
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server "
"could not comply with the request because the password is invalid."
msgstr ""

#: keystone/exception.py:121
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:130
msgid "(Disable debug mode to suppress these details.)"
msgstr ""

#: keystone/exception.py:135
#, python-format
msgid "%(message)s %(amendment)s"
msgstr ""

#: keystone/exception.py:143
msgid "The request you have made requires authentication."
msgstr "A requisição que você fez requer autenticação."

#: keystone/exception.py:149
msgid "Authentication plugin error."
msgstr "Erro do plugin de autenticação."

#: keystone/exception.py:157
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:162
msgid "Attempted to authenticate with an unsupported method."
msgstr "Tentativa de autenticação com um método não suportado."

#: keystone/exception.py:170
msgid "Additional authentications steps required."
msgstr "Passos de autenticação adicionais requeridos."

#: keystone/exception.py:178
msgid "You are not authorized to perform the requested action."
msgstr "Você não está autorizado à realizar a ação solicitada."

#: keystone/exception.py:185
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr ""

#: keystone/exception.py:190
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target "
"%(target)s"
msgstr ""

#: keystone/exception.py:195
#, python-format
msgid "Could not find: %(target)s"
msgstr ""

#: keystone/exception.py:201
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr ""

#: keystone/exception.py:208
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr "Uma exceção não tratada ocorreu: Não foi possível encontrar metadados."

#: keystone/exception.py:213
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr ""

#: keystone/exception.py:217
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr ""

#: keystone/exception.py:221
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr ""

#: keystone/exception.py:225
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr ""

#: keystone/exception.py:229
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:233
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr ""

#: keystone/exception.py:237
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr ""

#: keystone/exception.py:241
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr ""

#: keystone/exception.py:245
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr ""

#: keystone/exception.py:249
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr ""

#: keystone/exception.py:253
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:257
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:261
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr ""

#: keystone/exception.py:265
#, python-format
msgid "Could not find version: %(version)s"
msgstr ""

#: keystone/exception.py:269
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr ""

#: keystone/exception.py:273
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:278
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr ""

#: keystone/exception.py:285
msgid "Request is too large."
msgstr "Requisição é muito grande."

#: keystone/exception.py:292
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:295
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""

#: keystone/exception.py:318
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:324
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""
"URL de endpoint mal-formada (%(endpoint)s), veja o log de ERROS para "
"detalhes."

#: keystone/exception.py:329
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:334
msgid "The action you have requested has not been implemented."
msgstr "A ação que você solicitou não foi implementada."

#: keystone/exception.py:341
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:348
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:354
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/notifications.py:124
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:133
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/notifications.py:141
#, python-format
msgid "Callback: `%(callback)s` subscribed to event `%(event)s`."
msgstr ""

#: keystone/notifications.py:159
#, python-format
msgid ""
"Invoking callback %(cb_name)s for event %(service)s %(resource_type)s "
"%(operation)s for%(payload)s"
msgstr ""

#: keystone/notifications.py:225
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr "Falha ao enviar notificação %(res_id)s %(event_type)s"

#: keystone/notifications.py:296
#, python-format
msgid "CADF Event: %s"
msgstr ""

#: keystone/notifications.py:309
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/controllers.py:70
#, python-format
msgid "Authentication failed: %s"
msgstr "Autenticação falhou: %s"

#: keystone/assignment/controllers.py:104
#: keystone/assignment/controllers.py:218 keystone/identity/controllers.py:68
msgid "Name field is required and cannot be empty"
msgstr "Campo nome é requerido e não pode ser vazio"

#: keystone/assignment/controllers.py:141
#, python-format
msgid "User %(user_id)s in project %(project_id)s doesn't exist."
msgstr ""

#: keystone/assignment/controllers.py:159
msgid "Marker could not be found"
msgstr "Marcador não pôde ser encontrado"

#: keystone/assignment/controllers.py:170
msgid "Invalid limit value"
msgstr "Valor limite inválido"

#: keystone/assignment/controllers.py:473
msgid "Specify a domain or project, not both"
msgstr "Especifique um domínio ou projeto, não ambos"

#: keystone/assignment/controllers.py:478
msgid "Specify a user or group, not both"
msgstr "Epecifique um usuário ou grupo, não ambos"

#: keystone/assignment/controllers.py:692
#, python-format
msgid ""
"Group %(group)s not found for role-assignment - %(target)s with Role: "
"%(role)s"
msgstr ""
"Grupo %(group)s não encontrado para a atribuição de role - %(target)s com"
" Role: %(role)s"

#: keystone/assignment/core.py:244
#, python-format
msgid "Creating the default role %s because it does not exist."
msgstr "Criando o papel padrão %s porque ele não existe."

#: keystone/assignment/core.py:276
#, python-format
msgid "Removing role %s failed because it does not exist."
msgstr ""

#: keystone/assignment/core.py:344
msgid "delete the default domain"
msgstr ""

#: keystone/assignment/core.py:355
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/assignment/core.py:392
#, python-format
msgid ""
"Project %(projectid)s not found when deleting domain contents for "
"%(domainid)s, continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:405
#, python-format
msgid ""
"Group %(groupid)s not found when deleting domain contents for "
"%(domainid)s, continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:417
#, python-format
msgid ""
"User %(userid)s not found when deleting domain contents for %(domainid)s,"
" continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:529
#, python-format
msgid "Group %s not found, no tokens to invalidate."
msgstr ""

#: keystone/assignment/core.py:567
#, python-format
msgid "Project (%s)"
msgstr "Projeto (%s)"

#: keystone/assignment/core.py:569
#, python-format
msgid "Domain (%s)"
msgstr "Domínio (%s)"

#: keystone/assignment/core.py:571
msgid "Unknown Target"
msgstr "Alvo Desconhecido"

#: keystone/assignment/core.py:572
#, python-format
msgid ""
"Group (%(group)s), referenced in assignment for %(target)s, not found - "
"ignoring."
msgstr ""
"Grupo (%(group)s), referenciado na atribuição para %(target)s, não "
"encontrada - ignorando."

#: keystone/assignment/core.py:1013 keystone/common/controller.py:282
#: keystone/identity/core.py:228
#, python-format
msgid "Expected dict or list: %s"
msgstr "Esperado dict ou list: %s"

#: keystone/assignment/backends/kvs.py:199
#: keystone/assignment/backends/ldap.py:537
#: keystone/assignment/backends/sql.py:361
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr "Não é possível remover role que não foi concedido, %s"

#: keystone/assignment/backends/ldap.py:107
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:200
#: keystone/assignment/backends/ldap.py:244 keystone/catalog/core.py:80
#: keystone/common/ldap/core.py:1056 keystone/identity/backends/kvs.py:117
#: keystone/identity/backends/kvs.py:224
#, python-format
msgid "Duplicate ID, %s."
msgstr "ID duplicado, %s."

#: keystone/assignment/backends/ldap.py:208 keystone/common/ldap/core.py:1046
#: keystone/identity/backends/kvs.py:125 keystone/identity/backends/kvs.py:152
#: keystone/identity/backends/kvs.py:231 keystone/identity/backends/kvs.py:259
#, python-format
msgid "Duplicate name, %s."
msgstr "Nome duplicado, %s."

#: keystone/assignment/backends/ldap.py:246
#: keystone/assignment/backends/ldap.py:254
#: keystone/assignment/backends/ldap.py:258
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:305
#: keystone/assignment/backends/sql.py:145
msgid "Inherited roles can only be assigned to domains"
msgstr "Roles herdados podem ser atribuídos somente à domínios"

#: keystone/assignment/backends/ldap.py:514
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:520
#, python-format
msgid "Role %s not found"
msgstr "Role %s não localizada"

#: keystone/assignment/backends/ldap.py:631
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/assignment/backends/sql.py:132
#, python-format
msgid ""
"Unexpected combination of grant attributes - User, Group, Project, "
"Domain: %s"
msgstr ""

#: keystone/assignment/backends/sql.py:301
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/backends/sql.py:382
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/auth/controllers.py:57
#, python-format
msgid ""
"Cannot load an auth-plugin by class-name without a \"method\" attribute "
"defined: %s"
msgstr ""

#: keystone/auth/controllers.py:65
#, python-format
msgid "Driver requested method %(req)s does not match plugin name %(plugin)s."
msgstr ""

#: keystone/auth/controllers.py:70
#, python-format
msgid "Auth Plugin %s does not have a \"method\" attribute."
msgstr ""

#: keystone/auth/controllers.py:74
#, python-format
msgid ""
"Auth plugin %(plugin)s is requesting previously registered method "
"%(method)s"
msgstr ""

#: keystone/auth/controllers.py:118
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has "
"conflicting values %(new)s and %(old)s"
msgstr ""

#: keystone/auth/controllers.py:154
#, python-format
msgid "Project is disabled: %s"
msgstr "O projeto está desativado: %s"

#: keystone/auth/controllers.py:160 keystone/auth/plugins/password.py:41
#: keystone/token/core.py:80 keystone/token/core.py:96
#, python-format
msgid "Domain is disabled: %s"
msgstr "O domínio está desativado: %s"

#: keystone/auth/controllers.py:327
msgid "Scoping to both domain and project is not allowed"
msgstr "A definição de escopo para o domínio e o projeto não é permitida"

#: keystone/auth/controllers.py:330
msgid "Scoping to both domain and trust is not allowed"
msgstr "A definição de escopo para o domínio e a trust não é permitida"

#: keystone/auth/controllers.py:333
msgid "Scoping to both project and trust is not allowed"
msgstr "A definição de escopo para o projeto e a trust não é permitida"

#: keystone/auth/controllers.py:431
#, python-format
msgid ""
"User %(user_id)s doesn't have access to default project %(project_id)s. "
"The token will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:438
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s is disabled. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:447
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s not found. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:487
msgid "User not found"
msgstr "Usuário não localizado"

#: keystone/auth/plugins/external.py:46
msgid "No authenticated user"
msgstr "Nenhum usuário autenticado"

#: keystone/auth/plugins/external.py:56
#, python-format
msgid "Unable to lookup user %s"
msgstr "Não é possível consultar o usuário %s"

#: keystone/auth/plugins/external.py:107
msgid "auth_type is not Negotiate"
msgstr ""

#: keystone/auth/plugins/oauth1.py:38
#, python-format
msgid "%s not supported"
msgstr ""

#: keystone/auth/plugins/oauth1.py:56
msgid "Access token is expired"
msgstr "Token de acesso expirou"

#: keystone/auth/plugins/oauth1.py:70
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:47 keystone/token/core.py:72
#, python-format
msgid "User is disabled: %s"
msgstr "O usuário está desativado: %s"

#: keystone/auth/plugins/password.py:123
msgid "Invalid username or password"
msgstr "Nome de usuário ou senha inválidos"

#: keystone/catalog/controllers.py:154
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/catalog/controllers.py:206 keystone/catalog/controllers.py:265
#: keystone/identity/controllers.py:71
msgid "Enabled field must be a boolean"
msgstr "Campo habilitado precisa ser um booleano"

#: keystone/catalog/core.py:40
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr ""

#: keystone/catalog/core.py:44
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr "Endpoint mal formado %(url)s - chave desconhecida %(keyerror)s"

#: keystone/catalog/core.py:49
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:55
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/catalog/backends/templated.py:106
#, python-format
msgid "Unable to open template file %s"
msgstr "Não é possível abrir o arquivo de modelo %s"

#: keystone/common/authorization.py:56
msgid "RBAC: Invalid user data in v3 token"
msgstr ""

#: keystone/common/authorization.py:61
msgid "RBAC: Proceeding without project"
msgstr "RBAC: Continuando sem projeto"

#: keystone/common/authorization.py:100
msgid "RBAC: Invalid user data in v2 token"
msgstr ""

#: keystone/common/authorization.py:105
msgid "RBAC: Proceeding without tenant"
msgstr "RBAC: Continuando sem tenant"

#: keystone/common/base64utils.py:205 keystone/common/base64utils.py:278
#: keystone/common/base64utils.py:332
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:211
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:215
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:221
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:240 keystone/common/base64utils.py:261
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/controller.py:52
#, python-format
msgid "RBAC: Authorizing %(action)s(%(kwargs)s)"
msgstr "RBAC: Autorizando %(action)s(%(kwargs)s)"

#: keystone/common/controller.py:59
msgid "RBAC: using auth context from the request environment"
msgstr ""

#: keystone/common/controller.py:64
msgid "RBAC: building auth context from the incoming auth token"
msgstr ""

#: keystone/common/controller.py:75 keystone/middleware/core.py:271
msgid "RBAC: Invalid token"
msgstr "RBAC: Token inválido"

#: keystone/common/controller.py:104 keystone/common/controller.py:195
#: keystone/common/controller.py:597
msgid "RBAC: Bypassing authorization"
msgstr "RBAC: Efetuando bypass da autorização"

#: keystone/common/controller.py:151 keystone/common/controller.py:193
#: keystone/common/controller.py:615
msgid "RBAC: Authorization granted"
msgstr "RBAC: Autorização concedida"

#: keystone/common/controller.py:181
#, python-format
msgid "RBAC: Adding query filter params (%s)"
msgstr "RBAC: Incluindo parâmetros de filtro de consulta (%s)"

#: keystone/common/controller.py:544
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/controller.py:568
msgid "Invalid token in _get_domain_id_for_request"
msgstr "token inválido em _get_domain_id_for_request"

#: keystone/common/dependency.py:83
msgid "event_callbacks must be a dict"
msgstr ""

#: keystone/common/dependency.py:88
#, python-format
msgid "event_callbacks[%s] must be a dict"
msgstr ""

#: keystone/common/pemutils.py:223
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:242
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:298
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:302
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:377
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:389
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/serializer.py:203
msgid "Multiple truncation attributes found"
msgstr ""

#: keystone/common/utils.py:98
#, python-format
msgid "Truncating user password to %d characters."
msgstr ""

#: keystone/common/utils.py:196 keystone/credential/controllers.py:42
msgid "Invalid blob in credential"
msgstr "BLOB inválido na credencial"

#: keystone/common/utils.py:275
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""
"Erro configurando o ambiente de debug. Verifique que a opção --debug-url "
"possui o formato <host>:<port> e que o processo debugger está escutando "
"nesta porta."

#: keystone/common/wsgi.py:67
msgid "No bind information present in token"
msgstr "Nenhuma informação de associação presente no token"

#: keystone/common/wsgi.py:71
#, python-format
msgid "Named bind mode %s not in bind information"
msgstr "Modo de associação nomeado %s não está nas informações de associação"

#: keystone/common/wsgi.py:78
msgid "Kerberos credentials required and not present"
msgstr "credenciais Kerberos requerida mas ausente"

#: keystone/common/wsgi.py:82
msgid "Kerberos credentials do not match those in bind"
msgstr "Credenciais Kerberos não batem com as da associação"

#: keystone/common/wsgi.py:85
msgid "Kerberos bind authentication successful"
msgstr "Autenticação de associação Kerberos realizada com sucesso"

#: keystone/common/wsgi.py:88
#, python-format
msgid "Ignoring unknown bind for permissive mode: {%(bind_type)s: %(identifier)s}"
msgstr ""
"ignorando associação desconhecida para modo permissivo: {%(bind_type)s: "
"%(identifier)s}"

#: keystone/common/wsgi.py:92
#, python-format
msgid "Couldn't verify unknown bind: {%(bind_type)s: %(identifier)s}"
msgstr ""
"Não foi possível verificar associação desconhecida: {%(bind_type)s: "
"%(identifier)s}"

#: keystone/common/wsgi.py:181
#, python-format
msgid "arg_dict: %s"
msgstr "arg_dict: %s"

#: keystone/common/wsgi.py:215
#, python-format
msgid "Authorization failed. %(exception)s from %(remote_addr)s"
msgstr "Autorização falhou. %(exception)s de %(remote_addr)s"

#: keystone/common/wsgi.py:302
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:314
#, python-format
msgid "%s field(s) cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:325
msgid ""
"will not lookup trust as the request auth token is either absent or it is"
" the system admin token"
msgstr ""

#: keystone/common/wsgi.py:332
msgid "Invalid token in _get_trust_id_for_request"
msgstr ""

#: keystone/common/wsgi.py:528 keystone/tests/test_wsgi.py:335
msgid "The resource could not be found."
msgstr "O recurso não pôde ser localizado."

#: keystone/common/cache/core.py:54
#, python-format
msgid "CACHE_GET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:60
#, python-format
msgid "CACHE_GET_MULTI: \"%(keys)r\" Values: \"%(values)r\""
msgstr ""

#: keystone/common/cache/core.py:65
#, python-format
msgid "CACHE_SET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:70
#, python-format
msgid "CACHE_SET_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:75
#, python-format
msgid "CACHE_DELETE: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:78
#, python-format
msgid "CACHE_DELETE_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:96
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""
"Não é possível construir chave de configuração do cache. Formato esperado"
" \"<argname>:<value>\".  Pulando formato desconhecido: %s"

#: keystone/common/cache/core.py:104
#, python-format
msgid "Keystone Cache Config: %s"
msgstr "Configuração de Cache do Keystone: %s"

#: keystone/common/cache/core.py:119
msgid "region not type dogpile.cache.CacheRegion"
msgstr "região não é do tipo dogpile.cache.CacheRegion"

#: keystone/common/cache/core.py:149
#, python-format
msgid "Adding cache-proxy '%s' to backend."
msgstr "Adicionando cache-proxy '%s' ao backend."

#: keystone/common/cache/backends/mongo.py:231
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:236
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:241
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:252
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:260
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:275
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:301
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:310
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/cache/backends/mongo.py:403
#, python-format
msgid ""
"TTL index already exists on db collection <%(c_name)s>, remove index "
"<%(indx_name)s> first to make updated mongo_ttl_seconds value to be  "
"effective"
msgstr ""

#: keystone/common/environment/__init__.py:52
#, python-format
msgid "Environment configured as: %s"
msgstr "Ambiente configurado como: %s"

#: keystone/common/environment/eventlet_server.py:93
msgid "Server can only listen once."
msgstr ""

#: keystone/common/environment/eventlet_server.py:95
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr "Iniciando %(arg0)s em %(host)s:%(port)s"

#: keystone/common/environment/eventlet_server.py:171
msgid "Server error"
msgstr "Erro do Servidor"

#: keystone/common/kvs/core.py:61
#, python-format
msgid "Registering Dogpile Backend %(backend_path)s as %(backend_name)s"
msgstr ""

#: keystone/common/kvs/core.py:69
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:104
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:120
#, python-format
msgid "Importing class %s as KVS proxy."
msgstr ""

#: keystone/common/kvs/core.py:128
#, python-format
msgid "%s is not a dogpile.proxy.ProxyBackend"
msgstr ""

#: keystone/common/kvs/core.py:132
#, python-format
msgid "Adding proxy '%(proxy)s' to KVS %(name)s."
msgstr ""

#: keystone/common/kvs/core.py:139
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:156
#, python-format
msgid ""
"Non-expiring keys not supported/required by %(region)s backend; unable to"
" set key_mangler for backend: %(err)s"
msgstr ""

#: keystone/common/kvs/core.py:182
#, python-format
msgid "Using %(func)s as KVS region %(name)s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:192
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:194
#, python-format
msgid "Using default dogpile sha1_mangle_key as KVS region %s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:204
#, python-format
msgid "KVS region %s key_mangler disabled."
msgstr ""

#: keystone/common/kvs/core.py:233
#, python-format
msgid "KVS region configuration for %(name)s: %(config)r"
msgstr ""

#: keystone/common/kvs/core.py:346
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:350
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/core.py:374
#, python-format
msgid "KVS lock acquired for: %s"
msgstr ""

#: keystone/common/kvs/core.py:393
#, python-format
msgid "KVS lock released for: %s"
msgstr ""

#: keystone/common/kvs/core.py:395
#, python-format
msgid "KVS lock released (timeout reached) for: %s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:70
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(driver)s` is not a valid memcached backend. Valid drivers: "
"%(driver_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:180
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:153
msgid ""
"Referrals were returned and ignored. Enable referral chasing in "
"keystone.conf via [ldap] chase_referrals"
msgstr ""

#: keystone/common/ldap/core.py:173
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:183
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Opção de certificado LADP TLS inválida: %(option)s. Escolha uma de: "
"%(options)s"

#: keystone/common/ldap/core.py:195
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr "Escopo LDAP inválido: %(scope)s. Escolha um de: %(options)s"

#: keystone/common/ldap/core.py:488
msgid "Invalid TLS / LDAPS combination"
msgstr "Combinação TLS / LADPS inválida"

#: keystone/common/ldap/core.py:492
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr "Opção LDAP TLS_AVAIL inválida: %s. TLS não dsponível"

#: keystone/common/ldap/core.py:502
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr "tls_cacertfile %s não encontrada ou não é um arquivo"

#: keystone/common/ldap/core.py:514
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr "tls_cacertdir %s não encontrado ou não é um diretório"

#: keystone/common/ldap/core.py:521
#, python-format
msgid "LDAP TLS: invalid TLS_REQUIRE_CERT Option=%s"
msgstr "LDAP TLS: Opção TLS_REQUIRE_CERT inválida. Opção:%s"

#: keystone/common/ldap/core.py:745
msgid ""
"LDAP Server does not support paging. Disable paging in keystone.conf to "
"avoid this message."
msgstr ""
"O Servidor LDAP não suporta paginação. Desative a paginação em "
"keystone.conf para evitar esta mensagem."

#: keystone/common/ldap/core.py:925
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%s\". Format must be "
"<ldap_attribute>:<keystone_attribute>"
msgstr ""
"Mapeamento de atributo adicional inválido: \"%s\". O formato deve ser "
"<ldap_attribute>:<keystone_attribute>"

#: keystone/common/ldap/core.py:1025
#, python-format
msgid "LDAP %s create"
msgstr "Criação de LDAP %s"

#: keystone/common/ldap/core.py:1030
#, python-format
msgid "LDAP %s update"
msgstr "Atualização de LDAP %s"

#: keystone/common/ldap/core.py:1035
#, python-format
msgid "LDAP %s delete"
msgstr "Exclusão de LDAP %s"

#: keystone/common/ldap/core.py:1178
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr "Não é possível alterar %(option_name)s %(attr)s"

#: keystone/common/ldap/core.py:1245
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr ""

#: keystone/common/ldap/core.py:1303
#, python-format
msgid ""
"When deleting entries for %(search_base)s, could not delete nonexistent "
"entries %(entries)s%(dots)s"
msgstr ""

#: keystone/common/sql/core.py:219
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/core.py:400
msgid "Duplicate Entry"
msgstr ""

#: keystone/common/sql/core.py:416
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr ""

#: keystone/common/sql/migration_helpers.py:163
#: keystone/common/sql/migration_helpers.py:209
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/contrib/ec2/controllers.py:305
msgid "Token belongs to another user"
msgstr "O token pertence à outro usuário"

#: keystone/contrib/ec2/controllers.py:333
msgid "Credential belongs to another user"
msgstr "A credencial pertence à outro usuário"

#: keystone/contrib/endpoint_filter/backends/sql.py:46
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr "Endpoint %(endpoint_id)s não encontrado no projeto %(project_id)s"

#: keystone/contrib/example/core.py:64 keystone/contrib/example/core.py:73
#, python-format
msgid ""
"Received the following notification: service %(service)s, resource_type: "
"%(resource_type)s, operation %(operation)s payload %(payload)s"
msgstr ""

#: keystone/contrib/federation/utils.py:122
msgid "Federation token is expired"
msgstr ""

#: keystone/contrib/federation/utils.py:225
msgid "Could not map user"
msgstr ""

#: keystone/contrib/federation/utils.py:254
#, python-format
msgid "Ignoring user name %s"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:79
msgid "Cannot change consumer secret"
msgstr "Não é possível alterar segredo do consumidor"

#: keystone/contrib/oauth1/controllers.py:102
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:159
#: keystone/contrib/oauth1/backends/sql.py:267
msgid "User IDs do not match"
msgstr "ID de usuário não confere"

#: keystone/contrib/oauth1/controllers.py:166
msgid "Could not find role"
msgstr "Não é possível encontrar role"

#: keystone/contrib/oauth1/controllers.py:209
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:258
#: keystone/contrib/oauth1/controllers.py:334
msgid "Request token is expired"
msgstr "Token de requisição expirou"

#: keystone/contrib/oauth1/controllers.py:272
msgid "There should not be any non-oauth parameters"
msgstr "Não deve haver nenhum parâmetro não oauth"

#: keystone/contrib/oauth1/controllers.py:276
msgid "provided consumer key does not match stored consumer key"
msgstr ""
"Chave de consumidor fornecida não confere com a chave de consumidor "
"armazenada"

#: keystone/contrib/oauth1/controllers.py:280
msgid "provided verifier does not match stored verifier"
msgstr "Verificador fornecido não confere com o verificador armazenado"

#: keystone/contrib/oauth1/controllers.py:284
msgid "provided request key does not match stored request key"
msgstr ""
"Chave de requisição do provedor não confere com a chave de requisição "
"armazenada"

#: keystone/contrib/oauth1/controllers.py:288
msgid "Request Token does not have an authorizing user id"
msgstr "Token de Requisição não possui um ID de usuário autorizado"

#: keystone/contrib/oauth1/controllers.py:323
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:350
msgid "authorizing user does not have role required"
msgstr "Usuário autorizado não possui o role necessário"

#: keystone/contrib/oauth1/controllers.py:363
msgid "User is not a member of the requested project"
msgstr "Usuário não é um membro do projeto requisitado"

#: keystone/contrib/oauth1/backends/sql.py:88
msgid "Consumer not found"
msgstr "Consumidor não encontrado"

#: keystone/contrib/oauth1/backends/sql.py:183
msgid "Request token not found"
msgstr "Token de requisição não encontrado"

#: keystone/contrib/oauth1/backends/sql.py:247
msgid "Access token not found"
msgstr "Token de acesso não encontrado"

#: keystone/contrib/revoke/controllers.py:32
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/contrib/revoke/core.py:173 keystone/token/provider.py:121
#: keystone/token/provider.py:142 keystone/token/provider.py:220
#: keystone/token/provider.py:227 keystone/token/providers/common.py:609
msgid "Failed to validate token"
msgstr "Falha ao validar token"

#: keystone/credential/core.py:120
#, python-format
msgid "Deletion of credential is not required: %s"
msgstr ""

#: keystone/identity/controllers.py:97
msgid "Enabled field should be a boolean"
msgstr "Campo habilitado deve ser um booleano"

#: keystone/identity/controllers.py:138
#, python-format
msgid "Unable to remove user %(user)s from %(tenant)s."
msgstr "Não é possível remover usuário %(user)s de %(tenant)s."

#: keystone/identity/controllers.py:157
#, python-format
msgid "Unable to add user %(user)s to %(tenant)s."
msgstr "Não é possível adicionar usuário %(user)s em %(tenant)s."

#: keystone/identity/core.py:100
#, python-format
msgid "Invalid domain name (%s) found in config file name"
msgstr ""
"nome de domínio inválido (%s) encontrado no nome do arquivo de "
"configuração"

#: keystone/identity/core.py:124
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr "Não é possível localizar diretório de configuração de domínio: %s"

#: keystone/identity/core.py:138
#, python-format
msgid "Ignoring file (%s) while scanning domain config directory"
msgstr ""
"ignorando arquivo (%s) enquanto verifica diretório de configuração de "
"domínio"

#: keystone/identity/core.py:179
msgid ""
"Running an experimental and unsupported configuration "
"(domain_specific_drivers_enabled = True); this will result in known "
"issues."
msgstr ""
"Executando uma configuração experimental e não suportada "
"(domain_specific_drivers_enabled = True); isto irá resultar em problemas "
"conhecidos."

#: keystone/identity/backends/kvs.py:72 keystone/identity/backends/kvs.py:74
#: keystone/identity/backends/ldap.py:58 keystone/identity/backends/ldap.py:60
#: keystone/identity/backends/ldap.py:66 keystone/identity/backends/ldap.py:68
#: keystone/identity/backends/sql.py:104 keystone/identity/backends/sql.py:106
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/backends/kvs.py:178 keystone/identity/backends/kvs.py:187
msgid "User not found in group"
msgstr "Usuário não localizado no grupo"

#: keystone/identity/backends/ldap.py:97 keystone/identity/backends/sql.py:152
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/ldap.py:100
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:163
#, python-format
msgid ""
"Group member '%(user_dn)s' not found in '%(group_id)s'. The user should "
"be removed from the group. The user will be ignored."
msgstr ""
"Membro do grupo '%(user_dn)s' não encontrado em '%(group_id)s'. O usuário"
" deve ser removido do grupo. O usuário será ignorado."

#: keystone/identity/backends/ldap.py:178 keystone/identity/backends/sql.py:190
#: keystone/identity/backends/sql.py:208
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr ""

#: keystone/identity/backends/ldap.py:303
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr "Usuário %(user_id)s já é membro do grupo %(group_id)s"

#: keystone/middleware/core.py:276
msgid "Auth token not in the request header. Will not build auth context."
msgstr ""

#: keystone/middleware/core.py:281
msgid "Auth context already exists in the request environment"
msgstr ""

#: keystone/middleware/core.py:286
#, python-format
msgid "RBAC: auth_context: %s"
msgstr ""

#: keystone/openstack/common/gettextutils.py:320
msgid "Message objects do not support addition."
msgstr ""

#: keystone/openstack/common/gettextutils.py:330
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: keystone/openstack/common/lockutils.py:102
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: keystone/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecado: %s"

#: keystone/openstack/common/log.py:436
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr "Erro carregando configuração de logging: %(log_config)s: %(err_msg)s"

#: keystone/openstack/common/log.py:486
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "Recurso syslog deve ser um destes: %s"

#: keystone/openstack/common/log.py:729
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Chamada fatal à configuração deprecada: %(msg)s"

#: keystone/openstack/common/policy.py:96
msgid "The JSON file that defines policies."
msgstr ""

#: keystone/openstack/common/policy.py:99
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: keystone/openstack/common/policy.py:114
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr "Política não permite a realização de %s."

#: keystone/openstack/common/policy.py:208
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr "Regras devem ser uma instância de dict ou Rules, recebeu %s em seu lugar"

#: keystone/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr "Valor desconhecido '%(val)s', valores aceitáveis são: %(acceptable)s"

#: keystone/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: keystone/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr "formato de string inválido: %s"

#: keystone/openstack/common/versionutils.py:70
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""
"%(what)s está deprecado desde %(as_of)s em favor de %(in_favor_of)s e "
"pode ser removido em %(remove_in)s."

#: keystone/openstack/common/versionutils.py:74
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""
"%(what)s está deprecado desde %(as_of)s e pode ser removido em "
"%(remove_in)s. Ele não será substituído."

#: keystone/policy/backends/rules.py:99
#, python-format
msgid "enforce %(action)s: %(credentials)s"
msgstr "Aplica %(action)s: %(credentials)s"

#: keystone/tests/core.py:147
#, python-format
msgid "Failed to checkout %s"
msgstr "Falha ao fazer check out %s"

#: keystone/tests/fakeldap.py:325
#, python-format
msgid "FakeLdap delete item: dn=%s"
msgstr "Exclusão de item FakeLdap: dn=%s"

#: keystone/token/controllers.py:367
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr "Usuário %(u_id)s  não está autorizado para o tenant %(t_id)s"

#: keystone/token/controllers.py:384 keystone/token/controllers.py:387
msgid "Token does not belong to specified tenant."
msgstr "O token não pertence ao tenant especificado."

#: keystone/token/core.py:87
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:88
msgid ""
"[signing] token_format is deprecated. Please change to setting the "
"[token] provider configuration value instead"
msgstr ""

#: keystone/token/provider.py:96
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""
"keystone.conf não reconhecido [assinando] token_format: esperado 'UUID' "
"ou 'PKI'"

#: keystone/token/provider.py:218
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr "Erro inesperado ou token mal formado ao determinar validade do token: %s"

#: keystone/token/backends/kvs.py:54
msgid ""
"It is recommended to only use the base key-value-store implementation for"
" the token driver for testing purposes.  Please use "
"keystone.token.backends.memcache.Token or "
"keystone.token.backends.sql.Token instead."
msgstr ""

#: keystone/token/backends/kvs.py:129
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/backends/kvs.py:168
#, python-format
msgid "Token `%(token_id)s` is expired, removing from `%(user_key)s`."
msgstr ""

#: keystone/token/backends/kvs.py:177
#, python-format
msgid "Token `%(token_id)s` is revoked, removing from `%(user_key)s`."
msgstr ""

#: keystone/token/backends/kvs.py:202
#, python-format
msgid "Token `%s` is expired, not adding to the revocation list."
msgstr ""

#: keystone/token/backends/kvs.py:222
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/backends/kvs.py:236
#, python-format
msgid ""
"Removing `%s` from revocation list due to invalid expires data in "
"revocation list."
msgstr ""

#: keystone/token/backends/kvs.py:267
#, python-format
msgid ""
"Invalid token entry expected tuple of `(<token_id>, <expires>)` got: "
"`%(item)r`"
msgstr ""

#: keystone/token/backends/kvs.py:276
#, python-format
msgid "Invalid expires time on token `%(token_id)s`: %(expires)r"
msgstr ""

#: keystone/token/providers/common.py:182
#: keystone/token/providers/common.py:285
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr "O usuário %(user_id)s não tem acesso ao projeto %(project_id)s"

#: keystone/token/providers/common.py:187
#: keystone/token/providers/common.py:290
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr "O usuário %(user_id)s não tem acesso ao domínio %(domain_id)s"

#: keystone/token/providers/common.py:212
msgid "Trustor is disabled."
msgstr "O fiador está desativado."

#: keystone/token/providers/common.py:276
msgid "Trustee has no delegated roles."
msgstr "Fiador não possui roles delegados."

#: keystone/token/providers/common.py:336
msgid "User is not a trustee."
msgstr "Usuário não é confiável."

#: keystone/token/providers/common.py:432
msgid "Oauth is disabled."
msgstr "Oauth está desabilitado."

#: keystone/token/providers/common.py:534
msgid "Non-default domain is not supported"
msgstr "O domínio não padrão não é suportado"

#: keystone/token/providers/common.py:542
msgid "Domain scoped token is not supported"
msgstr "O token de escopo de domínio não é suportado"

#: keystone/token/providers/pki.py:45
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/pki.py:46 keystone/token/providers/pkiz.py:29
msgid "Unable to sign token."
msgstr "Não é possível assinar o token."

#: keystone/trust/controllers.py:132
msgid "Cannot create a trust with a token issued via delegation."
msgstr ""

#: keystone/trust/controllers.py:161
msgid "The authenticated user should match the trustor."
msgstr ""

#: keystone/trust/controllers.py:166
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:58
msgid "remaining_uses must be a positive integer or null."
msgstr ""

